version: '3'
services:
  web:
    build: .
    ports:
      - "4120:3000"
    image: maormendel/fr:100.01
  server:
    image: maormendel/bac:100.01
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"