FROM python:3.10.3


WORKDIR /app

COPY . .
RUN git clone https://github.com/yalikadman1/calander_optimization.git
WORKDIR /calander_optimization/server
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "app.py"]
